name 'jboss'
maintainer 'Evgeniy_Krupen'
maintainer_email 'evgeniy_krupen@epam.com'
license 'all_rights'
description 'Installs/Configures jboss'
long_description 'Installs/Configures jboss'
version '0.1.0'
depends 'java'
