# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
# config for web VM
	config.vm.define "web", primary: true do |web|
		web.vm.box = "sbeliakou/centos-6.7-x86_64"
		web.vm.hostname = "web"
		web.vm.network "private_network", ip: "192.168.25.10"
		web.vm.network "forwarded_port", guest: 80, host: 8081
                web.vm.network "forwarded_port", guest: 8080, host: 8080
		web.vm.provider "virtualbox" do |machine|
			machine.name = "chef"
			machine.cpus = 1
			machine.memory = 512
						end
		web.vm.provision "shell", inline: "echo This is Chev"
		web.vm.provision "shell", path: "chef.sh"
		end

  config.vm.box = "sbeliakou/centos-6.7-x86_64"

end
