# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define "web", primary: true do |web|
		web.vm.box = "ubuntu/trusty64"
		web.vm.hostname = "chef-server"
		web.vm.network "private_network", ip: "192.168.25.100"
		web.vm.network "forwarded_port", guest: 80, host: 8080
                web.vm.network "forwarded_port", guest: 443, host: 9443
		web.vm.provider "virtualbox" do |machine|
			machine.name = "chef"
			machine.cpus = 1
			machine.memory = 4096
		end
		web.vm.provision "shell", inline: "echo This is Chev"
		#web.vm.provision "shell", path: "chef.sh"
		end
#  config.vm.box = "sbeliakou/centos-6.7-x86_64"


         config.vm.define "web2", primary: true do |web2|
		web2.vm.box = "sbeliakou/centos-6.7-x86_64"
		web2.vm.hostname = "web2"
		web2.vm.network "private_network", ip: "192.168.25.10"
		web2.vm.network "forwarded_port", guest: 80, host: 8081
                web2.vm.network "forwarded_port", guest: 8080, host: 8082
		web2.vm.provider "virtualbox" do |machine|
			machine.name = "chef2"
			machine.cpus = 1
			machine.memory = 512
						end
		web2.vm.provision "shell", inline: "echo This is Chev"
#		web.vm.provision "shell", path: "chef.sh"
		end

end
